Numpy Learning 

In [7]:
import numpy as np

In [9]:
a = np.arange(6)
b = a[np.newaxis, :]
sh = b.shape
sh

(1, 6)

In [13]:
a = np.array([1,2,3,4,5,6])
tp = type(a)
print(f"==>> tp: {tp}")
print(a[-1])

==>> tp: <class 'numpy.ndarray'>
6


In [14]:
a = np.arange(2,20,2)
a 

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
a = np.linspace(0,20,num=8)    ## divide the array into equal parts 
a

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [24]:

a = np.ones(2,dtype=np.float16)
a

array([1., 1.], dtype=float16)

In [34]:
## for soting array 
a = np.random.random(20)*1000000000
b = np.random.random(20)*1000000000
a.sort()
b.sort()
tt = np.concatenate([[1,2,3,4,5],[6,7,8,9,]])
tt

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
x = np.arange(30)
print(f"==>> x: {x}")
y = np.arange(10,50,15)
print(f"==>> y: {y}")
tt = np.concatenate((x,y),axis=0)
print(f"==>> tt: {tt}")

==>> x: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
==>> y: [10 25 40]
==>> tt: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 10 25 40]


In [46]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

tt = np.concatenate((x, y), axis=0)
print(f"==>> tt: {tt}")
dimentoin = tt.ndim
print(f"==>> dimentoin: {dimentoin}")

==>> tt: [[1 2]
 [3 4]
 [5 6]]
==>> dimentoin: 2


In [48]:
tt.shape

(3, 2)

In [47]:
tt.size

6

In [49]:
tt.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
a = np.array([1, 2, 3, 4, 5, 6])
a2 = a[np.newaxis, :]
print(f"==>> a2.shape: {a2.shape}")
a2

==>> a2.shape: (1, 6)


array([[1, 2, 3, 4, 5, 6]])

In [52]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [53]:
print(a[a < 5])

[1 2 3 4]


In [55]:
five_up = (a >= 5)
print(f"==>> five_up: {five_up}")
print(a[five_up])

==>> five_up: [[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]
[ 5  6  7  8  9 10 11 12]


In [56]:
divisible_by_2 = a[a%2==0]  ## return true or false
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [57]:
c = a[(a > 2) & (a < 11)]
print(c)


[ 3  4  5  6  7  8  9 10]


In [58]:
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))


In [60]:
list_of_coordinates= list(zip(b[0], b[1]))
print(f"==>> list_of_coordinates: {list_of_coordinates}")

for coord in list_of_coordinates:
    print(coord)

==>> list_of_coordinates: [(0, 0), (0, 1), (0, 2), (0, 3)]
(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [61]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [62]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [63]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [64]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [65]:
np.hsplit(x, 3)   ## split array into three equally shaped arrays

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [66]:
# you wanted to split your array after the third and fourth column,
x = np.hsplit(x, (3, 4))
x

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [68]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [69]:
b1 = a[0, :]
b1

array([1, 2, 3, 4])

In [70]:
b1[0] = 99
b1

array([99,  2,  3,  4])

In [71]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# Now we create an array b1 by slicing a and modify the first element of b1. This will modify the corresponding element in a as well!

In [72]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [73]:
a = np.array([1, 2, 3, 4])

a.sum()

10

In [77]:
b = np.array([[1, 1], [3, 2]])
sm = b.sum(axis=0)
sm

array([4, 3])

In [78]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

In [ ]:
# Creating matrices


In [79]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])